name: 🚧 Integration
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  format:
    name: 💅 Check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        with:
          version: 8
      - uses: actions/setup-node@main
        with:
          cache: pnpm
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm prettier --check .
      - run: pnpm lint

  build:
    name: ⚛️ Build React application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        with:
          version: 8
      - uses: actions/setup-node@main
        with:
          cache: pnpm
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm build
